AllCops:
  TargetRubyVersion: 2.3
MethodLength:
  Max: 200

LineLength:
  Max: 225

AbcSize:
  Max: 125

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# I think we probably want to change this at some point
Style/SafeNavigation:
  Enabled: false

Style/ClassVars:
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
